name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: |
        git config --global user.email yorifuji@gmail.com
        git config --global user.name  github-actions
    - name: Checkout and Merge
      run: |
        git checkout gh-pages
        git merge origin/master
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
